- src/atlas/parallel/mpi/mpi.h
- src/tests/parallel/CMakeLists.txt
- src/tests/parallel/test_setcomm.cc
I would like to change temporarily Atlas communicator; I tried using eckit setDefaultComm, but without success. 
Atlas communicator is a static variable, initialized to eckit default communicator on startup : 
```
inline const Comm& comm() {
static const Comm& _comm = eckit::mpi::comm();
return _comm;
}
```
Should I change this to : 
```
inline const Comm& comm() {
return eckit::mpi::comm();
}
```
Or should I introduce a atlas::mpi::setDefaultComm function ?
> Try to change Atlas communicator using eckit setDefaultComm

- src/atlas/functionspace/detail/StructuredColumns_setup.cc
- src/tests/functionspace/CMakeLists.txt
- src/tests/functionspace/test_structuredcolumns_biperiodic.cc
X periodicity was already working, there was nothing to do. 
The config parameter "periodic_y" enables y-periodicity. Everything works, except that we get spurious coordinates in the halo on domain edges, but this should not be an issue as these coordinates are not defined. I have also added the "periodic_x" config parameter which could be useful in the future.
A test case has been added, which makes some basic checks; I could add some more if necessary.
> StructuredColumns with x/y bi-periodicity on regional grids

- src/atlas/grid/detail/distribution/BandsDistribution.h
- src/tests/grid/test_distribution_regular_bands.cc
The band distribution setup hangs when distributing a L160000x80000 grid on two tasks.
This branch solves the problem and implements a new test.
Please note that defining a L160000x80000 requires compiling Atlas with -DATLAS_BITS_LOCAL=64.
> Distribution setup hangs with L160000x80000

- src/atlas/grid/detail/partitioner/MatchingMeshPartitionerLonLatPolygon.cc
- src/atlas/library/config.h
- src/atlas/projection/detail/ProjectionImpl.h
- src/atlas/util/PolygonXY.cc
- src/atlas/util/detail/KDTree.h
- src/tests/projection/test_jacobian.cc
- src/tests/util/test_kdtree.cc
As discussed offline, I've added matrix-vector and matrix-scalar multiplication methods to `projection::Jacobian`. I've also added some constructors (there were none) and an output insertion operator. I've refactored the code to make it more compact wherever I could.
> Added multiplication methods to `projection::Jacobian`.

- src/atlas/redistribution/detail/RedistributeGeneric.cc
This is a minor feature update which removes the field rank restrictions in the redistribution class. Before, the class could only redistribute fields of rank 3, or lower. Now, it can redistribute all ranks supported by Atlas.
> Remove rank 3 restriction of redistribution class.

- src/atlas/grid/detail/distribution/SerialDistribution.cc
- src/atlas/grid/detail/distribution/SerialDistribution.h
JEDI-OOPS has a "round-robin" configuration, that evenly and randomly distributes observations across each MPI partition. I would like an atlas distribution to support this configuration for use in embarrassingly parallel applications - where each observation requires no communication with any other. The advantage of this is that it will increase the speed of the program whilst allowing for easy testing against domain-decomposed partitioning.
This change will create a copy of the mesh on each MPI parititon allowing atlas to be run in parallel for this kind of problem. I will then create a PointCloud functionspace containing the observation locations on that particular partition and interpolate the gridded data to these locations.
Please let me know if you think this is a bad idea, or if …
> Feature: Serial distribution to use entire mesh on every partition

- .github/workflows/reusable-ci-hpc.yml
Load fftw and eigen modules.
Remove openmpi as build-package-hpc does not support that yet.
> Fix `More processors requested than permitted` error on HPC

- .github/workflows/reusable-ci-hpc.yml
Fixes `--modules-package` input syntax for build-package-hpc.
> CI fix package modules input syntax

- src/atlas/field/FieldSet.cc
- src/atlas/field/FieldSet.h
<br>
This PR is intended to add a procedure to include _metadata_ in FieldSet.
<br><br>
All the tests pass.
<br><br>
> add procedure to include metadata in FieldSet

- src/atlas/interpolation/method/unstructured/ConservativeSphericalPolygonInterpolation.cc
- src/atlas/interpolation/method/unstructured/ConservativeSphericalPolygonInterpolation.h
- src/atlas/util/ConvexSphericalPolygon.cc
- src/atlas/util/ConvexSphericalPolygon.h
- src/sandbox/interpolation/atlas-conservative-interpolation.cc
- src/tests/interpolation/test_interpolation_conservative.cc
- src/tests/util/test_convexsphericalpolygon.cc
Fixing #129
- improvement in polygon intersection (more robust Sutherland-Hodgman algorithm)
- print out the worst under-covering and over-covering of target polygons
- output in JSON format
Remaining issue from #129
- searching of candidate source polygons to intersect a give target polygon should not be done via std::set and comparison of centroids to determine if two polygons are same. The coefficient ATLAS_COMPAREPOINTXYZ_EPS_FACTOR should be set to 1e4 for high grid res, but 1e8 for low mesh. This has to be removed in the future version.
> Improve robustness of conservative spherical polygon interpolation for high resolution meshes

- src/atlas/array/helpers/ArrayForEach.h
- src/tests/array/test_array_foreach.cc
Hi @wdeconinck,
I've found that the array ForEach method is particularly slow when processing small arrays (tested on N = 100). I believe this is because processing `execution_policy` configs has a relatively high amount overhead.
I've done a couple of things to alleviate this:
1) allowed `constexpr` policy selection when you provide an `execution_policy` object.
2) implemented perfect forwarding on the ArrayView objects (I don't think this did much, but it was useful to learn how to do it!)
I've added two performance tests :
1) `nested` performs a `ForEach` over the 50000 columns and another ForEach over the 100 levels. Execution policy selection is `constexpr`.
2) `nested, config`. Does the same as above, but determines the policy via a config.
```
Elapsed time: Addition; raw pointer …
```
> Optimise array::helpers::ForEach for small arrays.

- src/atlas/array/helpers/ArrayForEach.h
- src/tests/array/test_array_foreach.cc
Change 1
---------
It is best to use the execution::sequential_policy as the default. It has least surprises, and also matches the STL default for its algorithms.
Change 2
----------
It is expected that when we develop a `field::for_each_column` functionality with one-dimensional slices, we expect to be able to pass function arguments in Function (lambda) as:
- `array::LocalView<double, 1>` (read/write)
- `array::LocalView<double,1>&&` (read/write)
- `array::LocalView<const double, 1>` (read-only)
- `array::LocalView<const double,1>&&` (read-only)
- `const array::LocalView<double, 1>&`(read-only)
- `const array::LocalView<const double, 1>&` (read-only)
What is agreeable to not work is:
- `array::LocalView<double,1>&`
- `array::LocalView<const double, 1>&`
In order for this the first list …
> Updates to ArrayForEach

- .github/ci-hpc-config.yml
Add build configurations to test atlas and eckit with/without MPI.
> Add MPI on/off build configuration to matrix

- src/atlas/mesh/actions/BuildConvexHull3D.cc
Before commit 0c1fdd66, the `local_indices.clear()` was called _before_ the work of adding the triangles. Commit 0c1fdd66 introduced the `add_triangles` lambda and this moved the code so the clear is called _after_ adding the triangles. 
This change in the order of execution affects the lambda's check of `local_indices.size()` and subsequent logic, producing bad meshes:
This PR restores the original order, and fixes the meshes:
> Fix triangulations for stripack and qhull

- src/atlas/interpolation/method/knn/GridBox.h
MIR-632 Created accessors to the private data of the GridBox class. This modification allows to use GridBox in mir.
> MIR-632 added accessors for the GridBox class.

- src/atlas/meshgenerator/detail/CubedSphereDualMeshGenerator.cc
- src/atlas/meshgenerator/detail/CubedSphereMeshGenerator.cc
Improve logic to eliminate config exception message. This change uses the return `bool` value of `p.get` to detect success/failure.
In a downstream application, we have been seeing error messages like these (but the messages don't result in failures):
```
Exception: Bad operator: cubedsphere (String) method 'contains' not implemented ...
```
This change fixes this. I no longer see these error messages in the downstream application.
> Fix partitioner config exception message

- src/atlas/array/helpers/ArrayForEach.h
- src/tests/array/test_array_foreach.cc
This PR adds the following method to `src/atlas/array/helpers/ArrayForEach.h`:
```
/// brief   Construct ArrayForEach and call apply
///
/// details Construct an ArrayForEach<ItrDims...> using std::integer_sequence
///         <int, ItrDims...>. Remaining arguments are forwarded to apply
///         method.
template <int... ItrDims, typename... Args>
void arrayForEachDim(std::integer_sequence<int, ItrDims...>, Args&&... args) {
ArrayForEach<ItrDims...>::apply(std::forward<Args>(args)...);
}
```
Relevant tests are added to `src/tests/array/test_array_foreach.cc`.
This feature supports #168 and should be merged beforehand.
> Added arrayForEachDim method to simplify template metaprogramming.

- src/atlas/interpolation/method/sphericalvector/SphericalVector.cc
- src/atlas/util/Geometry.cc
- src/tests/interpolation/test_interpolation_spherical_vector.cc
- src/tests/util/test_unitsphere.cc
This draft PR updates the test from PR #168 to include halo exchanges. Due to issue #174, the following code has to be added before `Inderpolation::exectute` is called:
```
if (functionspace::StructuredColumns(sourceFunctionSpace)) {
sourceFieldSet[0].metadata().set("type", "scalar");
sourceFieldSet[0].haloExchange();
sourceFieldSet[0].metadata().set("type", "vector");
}
```
For other functionspaces, the type is set to `vector` and  the halo exchange is called within `Inderpolation::exectute`.
If you comment out this block, you'll reproduce the output in #174 .
Once #174 is addressed, this block can be deleted and the PR will be ready for review.
Edit: further additions to this PR will close #174
> Update `SphericalVector` to work with StructuredColumns as source functionspace.

- src/atlas/functionspace/PointCloud.cc
I've tried matching the arguments to the signatures types (maybe there should only be one GatherScatter::setup). This seems to have been a requirement put forward for production ("for O8000" is the comment), so as far as I can tell is is urgent.
> Fix build for configuration setting ATLAS_BITS_LOCAL=64

- atlas_io/CMakeLists.txt
- atlas_io/eckit_codec_adaptor/CMakeLists.txt
- atlas_io/eckit_codec_adaptor/src/CMakeLists.txt
- atlas_io/eckit_codec_adaptor/src/atlas_io/CMakeLists.txt
- atlas_io/eckit_codec_adaptor/src/atlas_io/Trace.cc
- atlas_io/eckit_codec_adaptor/src/atlas_io/Trace.h
- atlas_io/eckit_codec_adaptor/src/atlas_io/atlas-io.h
- atlas_io/eckit_codec_adaptor/src/atlas_io/detail/BlackMagic.h
- atlas_io/tests/TestEnvironment.h
- atlas_io/tests/test_io_stream.cc
When eckit is compiled with feature ECKIT_CODEC enabled, then atlas_io will with this PR now delegate all calls to eckit_codec.
This ensures a smooth transition for downstream projects of atlas_io (such as atlas-orca, multio) to migrate to use eckit_codec directly.
This PR supersedes PR #180
> atlas_io is an adaptor library when eckit_codec is available

- src/atlas/interpolation/element/Triag2D.cc
Most floating-point numbers in this context are `double`, but there's a surprise `float` in the `Triag2D::intersects` algorithm. This lowers the precision of the `double` u,v coordinates.
I tried writing my own interpolation algorithm from the intersection outputs, and found I needed looser tolerances everywhere as a result of this `float` when using LonLat/2D triangles as compared to the Spherical/3D triangles.
Assuming this to be an oversight, I'm making this PR... let me know if the `float` is intentional.
> Remove float in Triag2D intersection algorithm

- .github/workflows/ci.yml
There's a weird problem with gh actions...
The `always()` should make the notification trigger even when some dependencies listed in `needs` fail. However we have to pull the evaluation in the ${{ }} to make it work.
> Update ci.yml to fix notification

- src/atlas/field/FieldSet.cc
- src/atlas/field/FieldSet.h
- src/tests/field/test_fieldset.cc
This should address #194 
An exception is thrown when accessing a field by name in the fieldset, when the name is ambiguous.
A unit-test is created that demonstrates the exception.
> Avoid silent errors accessing Fieldset fields by ambiguous names

- src/atlas/interpolation/method/unstructured/UnstructuredBilinearLonLat.cc
Recent work on adding a halo size > 0 to atlas-orca (https://github.com/ecmwf/atlas-orca/issues/19) revealed an issue in the North fold of the orca grid when comparing MPI to non-MPI interpolations.
This issue was traced to the interpolator not properly accounting fully for the wrapping of the source interpolation mesh cell when it crosses the periodic boundary.
This change fixes this issue by properly validating each cell.
The change was proposed by Simon Good, I am just performing the necessary admin to get the change into atlas.
This is tricky to test, and requires a separate PR in atlas-orca to introduce a ctest to cover the issue.
* A ctest will be added as part of https://github.com/ecmwf/atlas-orca/pull/20
* Testing was performed using a combination build, as part of other changes …
> Wrap out-of-bounds source cells into the domain

- src/atlas_f/field/atlas_Field_module.fypp
- src/atlas_f/grid/atlas_Grid_module.F90
- src/atlas_f/mesh/atlas_MeshBuilder_module.F90
Resolves #212.  There are three types of change:
1)
Addition of target attribute to some variables (see e.g. https://github.com/ecmwf/fckit/pull/43)
2)
In array_c_to_f (in atlas_Field_module.fypp) the call to c_f_pointer is sometimes passing a shape where one of the bounds is 0.  This results in tmp being null, meaning that subsequent array slices being pointed at by array_fptr are invalid.  I have addressed this by allocated a 0 size array.
3)
atlas_fctest_field_wrap was failing like this:
/spice/scratch/frwd/cylc-run/mi-be984/work/1/git_clone_atlas/atlas/src/tests/field/fctest_field_wrap.F90:116: warning: FCTEST_CHECK_EQUAL(data(i,j,l) , real(1000*i+100*j+10*k+l,c_double) )
--> [   1.1210000000000000E+03 !=   1.1120000000000000E+03 ]
I tracked this down to the function array_strides …
> NAG fixes.

- src/atlas/field/detail/FieldImpl.h
`FieldImpl.h` used `std::find`, but did not include the `algorithm` header. This lead to some compilation errors in atlas4py with gcc 14.1.1.
> Fix missing header in FieldImpl.h

- src/atlas/functionspace/Spectral.h
This PR fixes a small typo in a comment that describes the structure of the Spectral FunctionSpace. 
None
> Fix typo in commented description of the spectral functionspace

- src/atlas/functionspace/detail/StructuredColumns.cc
- src/atlas/interpolation/method/sphericalvector/ComplexMatrixMultiply.h
- src/tests/interpolation/test_interpolation_spherical_vector.cc
This is a set of minor bug-fixes
The most notable (and contentious) is that for the vector interpolation it is currently assuming that the `levels` have been given to StructuredColumns at construction. For most functionspaces this is not the case, so I have added a small change that will allow the changing of the sign in the 3D case, when `levels` is not set in the functionspace but instead in the field.
I have added a number of additional tests to `test_interpolation_spherical_vector.cc` including the classic Gauss state and cubic interpolation.
> Bug fixes to vector interpolation with StructuredColumns and spherical vector interpolation

- cmake/features/ACC.cmake
- cmake/project_summary.cmake
- src/atlas/CMakeLists.txt
- src/atlas/array/gridtools/GridToolsArray.cc
- src/atlas/array/gridtools/GridToolsDataStore.h
- src/atlas/parallel/acc/acc.cc
- src/atlas_acc_support/CMakeLists.txt
- src/atlas_acc_support/atlas_acc.F90
- src/atlas_acc_support/atlas_acc.cc
- src/atlas_acc_support/atlas_acc.h
- src/atlas_f/CMakeLists.txt
- src/sandbox/fortran_acc_fields/CMakeLists.txt
- src/tests/acc/CMakeLists.txt
- src/tests/acc/fctest_unified_memory_with_openacc_cxx.cc
- src/tests/array/test_array.cc
- src/tests/field/CMakeLists.txt
- src/tests/field/test_field_acc.cc
The Atlas ACC feature was not working on Cray compilers because only the Fortran compiler supports OpenACC. This means that functions like `acc_map_data` with Cray could only be called via C-bindings.
This PR adapts 'atlas_acc_support` library to use C-bindings to a Fortran implementation when the C++ compiler ID is not "NVHPC".
Additionally some cleanup of the use of OpenACC_Fortran_FLAGS is done.
> Support OpenACC with Cray compiler + use OpenACC_Fortran_FLAGS

- src/atlas/array/ArrayViewVariant.cc
- src/atlas/array/ArrayViewVariant.h
- src/atlas/runtime/Exception.h
This PR does some tidying that I missed in PR #220. Namely headers and the error message. I also found a missing `<sstream>` header in `runtime/Exception.h`.
> Tidied up headers in `ArrayViewVariant.h` and `ArrayViewVariant.cc`

- src/atlas/functionspace/detail/StructuredColumns.cc
- src/tests/interpolation/test_interpolation_spherical_vector.cc
Whilst integrating `util::pack_vector_fields` into the `SphericalVector` interpolation method, I uncovered a bug in `StructuredColumns`. The methods `fixup_halos` and `halo_exchange.execute_adjoint` were called in the wrong order during a halo exchange adjoint. This PR fixes the bug.
I'd initially missed this by adding (and then forgetting) a workaround in the `SphericalVector` test.
@MarekWlasak this will likely be of interest to you.
> Fixed ordering of `fixup_halos` and `halo_exhange.execute_adjoint` in `StructuredColumns.cc`

- src/atlas/util/PackVectorFields.cc
This PR refactors `util::pack_vector_fields` to use `std::variant<ArrayViews...>` with `std::visit`, as opposed to nested `switch` statements to resolve the possible `Value` types and `Rank` values for different arrays.
I also found it beneficial to refactor `array::make_view_variant` such that it produces either a variant of `const` or a variant of `non- const` ArrayView types.
This PR needs #220 and #224 to be merged first.
> Refactor `util::pack_vector_fields` to use `array::ArrayViewVariant`

- src/atlas/interpolation/method/sphericalvector/SphericalVector.cc
This is the last of this batch of PRs that refactors the `SphericalVector` interpolation method. Here we've used `std::visit` on `ArrayViewVariant` to resolve the rank and type of the arrays instead of several verbose `if` statements and function overloads.
This PR depends on PRs #220, #223, #224 and #226. It closes issue #217.
> Refactor `SphericalVector` interpolation method to use `array::ArrayViewVariant`.

- src/atlas/array/Array.h
- src/atlas/array/ArraySpec.cc
- src/atlas/array/ArraySpec.h
- src/atlas/array/native/NativeMakeView.cc
- src/atlas/field/detail/FieldImpl.h
- src/atlas/field/detail/FieldInterface.cc
- src/atlas/field/detail/FieldInterface.h
- src/atlas_f/field/atlas_FieldSet_module.fypp
- src/atlas_f/field/atlas_Field_module.fypp
- src/tests/field/CMakeLists.txt
- src/tests/field/fctest_field_gpu.F90
- src/tests/field/fctest_fieldset_gpu.F90
- src/tests/field/test_field_acc.cc
* add access to the device pointer in atlas_Field_module and atlas_FieldSet_module for the 'deviceptr' clause of OpenACC
* add sync_host_device;
> Add Fortran access to device data through Field and FieldSet

- src/atlas/interpolation/method/structured/StructuredInterpolation2D.h
- src/atlas/interpolation/method/structured/StructuredInterpolation2D.tcc
- src/atlas/interpolation/method/structured/kernels/CubicHorizontalKernel.h
- src/atlas/interpolation/method/structured/kernels/CubicHorizontalLimiter.h
- src/atlas/interpolation/method/structured/kernels/LinearHorizontalKernel.h
- src/atlas/interpolation/method/structured/kernels/QuasiCubicHorizontalKernel.h
- src/tests/interpolation/CMakeLists.txt
- src/tests/interpolation/test_interpolation_structured2D_limiter.cc
This fixes an issue where the "limiter" configuration for StructuredInterpolation2D was not having any effect.
The fix is to propagate the option to the underlying Kernel.
Also an error is thrown when the "limiter" option is used in conjunction with the use of a matrix, as that is not supported.
So to enable the limiter one should both set "matrix_free=true" and "limiter=true".
> Fix application of limiter for StructuredInterpolation2D

- src/atlas/grid/detail/partitioner/MatchingFunctionSpacePartitionerLonLatPolygon.cc
What happened
----------------
FE_DIV_BY_ZERO reported by @cducher with following reproducer:
```c++
/*
To run:
mpirun -np 2 --use-hwthread-cpus $exe_dir/atlas_bug.x
*/
#include <vector>
#include "atlas/library.h"
#include "atlas/parallel/mpi/mpi.h"
#include "atlas/meshgenerator.h"
#include "atlas/grid.h"
#include "atlas/grid/Grid.h"
#include "atlas/grid/StructuredGrid.h"
#include "atlas/grid/detail/grid/Gaussian.h"
#include "atlas/grid/Distribution.h"
#include "atlas/grid/Vertical.h"
#include "atlas/functionspace/StructuredColumns.h"
#include "atlas/functionspace/NodeColumns.h"
#include "atlas/field/Field.h"
int gridSizeX_{32};  // grid size X
int gridSizeY_{64};  // grid size Y
int nHalo_{3};       // N halo points
int nLevels_{19};
atlas::functionspace::StructuredColumns …
```
> bugfix: DIV_BY_ZERO in MatchingFunctionSpacePartitionerLonLatPolygon

- hic/CMakeLists.txt
- hic/src/CMakeLists.txt
- hic/src/hic/hic_dummy/dummyShouldNotBeCalled.h
- hic/src/hic/hic_dummy/hic_dummy_runtime.h
- hic/src/hic/hic_dummy/hicsparse_dummy.h
- hic/src/hic/hic_library_types.h
- hic/src/hic/hic_namespace_macro.h
- hic/src/hic/hic_runtime.h
- hic/src/hic/hicsparse.h
- hic/tests/CMakeLists.txt
- hic/tests/test_hicsparse.cc
This PR adds wrappers for parts of cuSparse and hipSparse to hic.
> Add wrappers for cu/hipsparse to hic

- src/atlas/interpolation/method/Method.cc
- src/atlas/linalg/sparse/SparseMatrixMultiply.h
- src/atlas/linalg/sparse/SparseMatrixMultiply.tcc
- src/atlas/linalg/sparse/SparseMatrixMultiply_EckitLinalg.cc
- src/atlas/linalg/sparse/SparseMatrixMultiply_EckitLinalg.h
- src/atlas/linalg/sparse/SparseMatrixMultiply_OpenMP.cc
- src/atlas/linalg/sparse/SparseMatrixMultiply_OpenMP.h
- src/tests/linalg/test_linalg_sparse.cc
This PR extends Atlas's sparse linear algebra interface with multiply-add functionality.
> Extend sparse linear algebra interface with multiply-add

- src/atlas/array/native/NativeArray.cc
- src/atlas/array/native/NativeDataStore.h
- src/tests/field/fctest_field_wrap_gpu.F90
* offloading discontiguous data via WrappedDataStorage
* Field can wrap discontiguous array and copy it to a contiguous memory on the device
> Offloading discontiguous host data

- src/atlas/CMakeLists.txt
- src/tests/CMakeLists.txt
- src/tests/linalg/test_linalg_sparse_matrix_gpu.cc
When not defining CUDAHOSTCXX , nvcc uses by default "g++" as the host compiler.
CMake does not have any introspection on the CUDA_HOST_COMPILER, and so we cannot add linker options that could be specific for CUDA - linked executables. 
This PR makes the HIC (so CUDA) tests link with the C++ linker, and avoids passing ACC_LINK_OPTIONS to the CUDA_HOST_COMPILER
> Fix for using default CUDA host compiler

- src/atlas/CMakeLists.txt
- src/atlas/linalg/sparse/Backend.cc
- src/atlas/linalg/sparse/Backend.h
- src/atlas/linalg/sparse/SparseMatrixMultiply.h
- src/atlas/linalg/sparse/SparseMatrixMultiply.tcc
- src/atlas/linalg/sparse/SparseMatrixMultiply_HicSparse.cc
- src/atlas/linalg/sparse/SparseMatrixMultiply_HicSparse.h
- src/tests/linalg/CMakeLists.txt
- src/tests/linalg/helper_linalg_sparse.h
- src/tests/linalg/test_linalg_sparse.cc
- src/tests/linalg/test_linalg_sparse_gpu.cc
This PR adds a hicsparse backend to the sparse matrix multiplication routines of linalg sparse.
This PR depends on https://github.com/ecmwf/atlas/pull/247 and the branch of this PR is currently based on the branch of https://github.com/ecmwf/atlas/pull/247.
Notes:
- This PR previously depended on https://github.com/ecmwf/atlas/pull/241 but that dependency is nolonger necessary as https://github.com/ecmwf/atlas/pull/247 will superseded the former PR.
> Add a hicsparse backend to linalg sparse

- src/atlas/trans/local/TransLocal.cc
- src/tests/trans/fctest_trans_unstructured.F90
This fixes #249 .
The problem was that the functionspace::Spectral created via the TransLocal api was creating a new functionspace with truncation == 1. 
This was due to an older removed API that could create the Spectral functionspace using a Trans object. An implicit conversion to 1 of this object resulted in truncation == 1.
> Fix creation of spectral function space from TransLocal (fixes #249)

- src/atlas/functionspace/detail/StructuredColumns.cc
- src/atlas/functionspace/detail/StructuredColumns_create_remote_index.cc
- src/atlas/interpolation/AssembleGlobalMatrix.cc
fix inconsistent usage of remote index in functionspace::StructureColumns
> Fix inconsistent index-base used in StructuredColumns::remote_index

- src/atlas/array/native/NativeArray.cc
- src/atlas/array/native/NativeDataStore.h
- src/tests/field/fctest_field_wrap_gpu.F90
- src/tests/field/test_field_acc.cc
This allows to offload existing wrapped data which may discontiguous as a slice of a larger array. This is e.g. the case when using a Multifield.
It makes use of HIC.
This is co-developed with @sbrdar
> Add offloading of discontiguous arrays

- pluto/src/pluto/memory_resource.h
- pluto/src/pluto/memory_resource/MemoryPoolResource.cc
- src/atlas/array/ArraySpec.cc
- src/atlas/array/ArraySpec.h
- src/atlas/array/native/NativeDataStore.h
- src/atlas/field/detail/FieldImpl.cc
- src/atlas/library/Library.cc
- src/tests/field/CMakeLists.txt
- src/tests/field/test_field_memory_resource.cc
NOTE, this PR applies only to `atlas::array::Array`, which also underpins `atlas::Field`!
Until now atlas was using a fixed strategy for host and device allocations in the atlas::array::Array
- host -> At least 64-byte aligned memory allocation, via `posix_memalign` (before #270) or 256-byte aligned `pluto::host_resource()` after.
- device -> `cudaMalloc` or `hipMalloc` via `hicMalloc` (before #270) or `pluto::device_resource()` after.
With this PR we now use:
- host -> `pluto::host::get_default_resource()`
- device -> `pluto::device::get_default_resource()` 
Suppose we want to use a pool of pinned memory for the host, and a pool of device memory for device. This makes for fast host-device memory transfers.
We can setup this up with C++:
- Using `pluto::memory_resource*` argument: 
```c++ …
```
> Use pluto default memory resources in atlas::array

- pluto/tests/CMakeLists.txt
- src/atlas/field/detail/MultiFieldInterface.cc
- src/atlas/functionspace/Spectral.h
- src/tests/field/fctest_multifield_ifs.F90
- src/tests/grid/test_largegrid.cc
- src/tests/projection/CMakeLists.txt
- src/tests/trans/CMakeLists.txt
- src/tests/trans/test_trans.cc
There are a number of issues when using nvidia 24.5, mostly with the RelWithDebInfo build type.
Some are compiler or linker bugs, but some are also due to bad practice or real bugs.
> Support nvidia 24.5

- src/atlas/mesh/MeshBuilder.cc
- src/atlas/mesh/MeshBuilder.h
- src/atlas/mesh/detail/MeshBuilderIntf.cc
- src/atlas/mesh/detail/MeshBuilderIntf.h
- src/atlas_f/mesh/atlas_MeshBuilder_module.F90
- src/tests/functionspace/test_functionspace.cc
- src/tests/mesh/fctest_mesh_triangular_mesh_builder.F90
- src/tests/mesh/test_mesh_builder.cc
- src/tests/mesh/test_mesh_builder_parallel.cc
- src/tests/mesh/test_mesh_triangular_mesh_builder.cc
Updates to the MeshBuilder and TriangularMeshBuilder API
- Changes to allow to use arbitrary indexing base for global_index (e.g. 0-based or 1-based) to define nodes, elements and connectivities.
- API that uses mdspan
- Fixes to allow strided node-coordinates
- Allow Fortran array slices for (strided) coordinates in TriangularMeshBuilder
@fmahebert this may be affecting you. Previous APIs are still working but are deprecated, with a compiler warning.
Just adding a `global_index_base` argument should remove the warning.
💣💥☠️ Static Analyzer Report ☠️💥💣
https://sites.ecmwf.int/docs/atlas/static-analyzer/PR-305
> Update MeshBuilder API

- src/atlas/interpolation/method/unstructured/ConservativeSphericalPolygonInterpolation.cc
- src/atlas/interpolation/method/unstructured/ConservativeSphericalPolygonInterpolation.h
- src/atlas/util/ConvexSphericalPolygon.cc
- src/atlas/util/ConvexSphericalPolygon.h
- src/sandbox/interpolation/atlas-conservative-interpolation.cc
- src/tests/interpolation/test_interpolation_conservative.cc
A 40% computational improvements in spherical polygon intersections.
Benchmark:
./atlas/src/sandbox/interpolation/atlas-conservative-interpolation --source.grid S964x432 --target.grid O128)
on Atos HPC/ECMWF with:
build type      : Release
timestamp     : 20250829113802
c++ compiler     : IntelLLVM 2025.0.4
flags          :  -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -fno-finite-math-only -O3 -DNDEBUG
The old develop needs 13.56s in the intersect_polygon subroutine, whereas the new one only 7.78s.
(co-developed with Willem Deconinck <willem.deconinck@ecmwf.int>)
💣💥☠️ Static Analyzer Report ☠️💥💣
https://sites.ecmwf.int/docs/atlas/static-analyzer/PR-310
> Improvement in spherical-polygon intersection

- src/atlas/array/Array.h
- src/atlas/array/ArrayDataStore.h
- src/atlas/array/native/NativeDataStore.h
- src/atlas/field/Field.cc
- src/atlas/field/Field.h
- src/atlas/field/FieldSet.cc
- src/atlas/field/FieldSet.h
- src/atlas/field/detail/FieldImpl.h
- src/atlas/field/detail/FieldInterface.cc
- src/atlas/field/detail/FieldInterface.h
- src/atlas/linalg/sparse/SparseMatrixStorage.cc
- src/atlas/linalg/sparse/SparseMatrixStorage.h
- src/atlas_f/field/atlas_FieldSet_module.fypp
- src/atlas_f/field/atlas_Field_module.fypp
- src/tests/field/fctest_fieldset_gpu.F90
Add `Field::syncHost` and `Field::syncDevice` functions.
- `field.syncHost()` is equivalent to `if (field.hostNeedsUpdate()) { field.updateHost(); }`
- `field.syncDevice()` is equivalent to `if (field.deviceNeedsUpdate()) { field.updateDevice(); }`
This also applies to `atlas::Array` and `atlas::FieldSet`
Fortran interfaces are also created for FieldSet and Field.
💣💥☠️ Static Analyzer Report ☠️💥💣
https://sites.ecmwf.int/docs/atlas/static-analyzer/PR-311
> Add Field::syncHost and Field::syncDevice

- pluto/src/pluto/copy.h
- pluto/src/pluto/trace.cc
- pluto/src/pluto/trace.h
- src/atlas/array/native/NativeDataStore.h
- src/atlas/linalg/sparse/MakeSparseMatrixStorageEckit.h
- src/atlas/linalg/sparse/MakeSparseMatrixStorageEigen.h
- src/atlas/linalg/sparse/SparseMatrixStorage.cc
- Adds PLUTO_TRACE output for pointers being copied between host/device.
- Adds ATLAS_TRACE output for Atlas arrays and fields for device allocations, device deallocations, update_device, update_host
To enable the ATLAS_TRACE output here, use the environment variable ATLAS_TRACE_MEMORY=ON
> Add more GPU tracing capabilities for device allocations and host-device data transfers

- cmake/features/CUDA.cmake
- src/atlas/functionspace/detail/StructuredColumns.cc
- src/atlas/library/defines.h.in
- src/atlas/parallel/HaloExchange.h
The on_device halo exchanges are now checking that the fields are marked as up-to-date on device.
When GPU_AWARE_MPI feature is disabled, then halo exchanges always happen on host with data copied to host and back to device.
For HaloExchange::execute_adjoint,  on_device is not implemented, and the route via the host is always used.
Also fix for StructuredColumsn::haloExchange which was not respecting the on_device flag.
> Improve HaloExchange on_device, checking state flags
